name: ${name}
version: ${version}
main: org.cubex.hammr.HammrEnhance
api-version: "1.21"
authors: [CubeX, AdLamb, FZAoao]
website: https://github.com/AdLambXD/Hammr
description: 下界合金装备铁砧强化系统
soft-depend:
  - Vault

commands:
  hammr:
    description: HammrEnhance 管理命令
    usage: /hammr <set|remove|give|reload>
    permission: hammr.admin

permissions:
  hammr.admin:
    description: 允许使用所有 HammrEnhance 管理命令
    default: op
